// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using U5_W1_D5poliziaMunicipale.Models.Entities;

#nullable disable

namespace U5_W1_D5poliziaMunicipale.Migrations
{
    [DbContext(typeof(MulteDbContext))]
    [Migration("20251205153950_MuleDb")]
    partial class MuleDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("U5_W1_D5poliziaMunicipale.Models.Entities.Anagrafica", b =>
                {
                    b.Property<Guid>("AnagraficaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cap")
                        .HasColumnType("int");

                    b.Property<string>("Citta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodiceFiscale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VerbaleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AnagraficaId");

                    b.HasIndex("VerbaleId");

                    b.ToTable("Anagrafiche");
                });

            modelBuilder.Entity("U5_W1_D5poliziaMunicipale.Models.Entities.Verbale", b =>
                {
                    b.Property<Guid>("VerbaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataTrascrizione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataViolazione")
                        .HasColumnType("datetime2");

                    b.Property<int>("DecurtazionePunti")
                        .HasColumnType("int");

                    b.Property<decimal>("ImportoMulta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IndirizzoViolazione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NominativoAgente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ViolazioneId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VerbaleId");

                    b.HasIndex("ViolazioneId");

                    b.ToTable("Verbali");
                });

            modelBuilder.Entity("U5_W1_D5poliziaMunicipale.Models.Entities.Violazione", b =>
                {
                    b.Property<Guid>("ViolazioneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescrizioneViolazione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ViolazioneId");

                    b.ToTable("Violazioni");
                });

            modelBuilder.Entity("U5_W1_D5poliziaMunicipale.Models.Entities.Anagrafica", b =>
                {
                    b.HasOne("U5_W1_D5poliziaMunicipale.Models.Entities.Verbale", "Verbale")
                        .WithMany("Anagrafiche")
                        .HasForeignKey("VerbaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Verbale");
                });

            modelBuilder.Entity("U5_W1_D5poliziaMunicipale.Models.Entities.Verbale", b =>
                {
                    b.HasOne("U5_W1_D5poliziaMunicipale.Models.Entities.Violazione", "Violazione")
                        .WithMany("Verbali")
                        .HasForeignKey("ViolazioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Violazione");
                });

            modelBuilder.Entity("U5_W1_D5poliziaMunicipale.Models.Entities.Verbale", b =>
                {
                    b.Navigation("Anagrafiche");
                });

            modelBuilder.Entity("U5_W1_D5poliziaMunicipale.Models.Entities.Violazione", b =>
                {
                    b.Navigation("Verbali");
                });
#pragma warning restore 612, 618
        }
    }
}
